helmfiles:
  - ./helmfiles/metrics-server/helmfile.yaml
  - ./helmfiles/fluentd/helmfiles.yaml
  - ./helmfiles/prometheus/helmfile.yaml
  - ./helmfiles/elasticsearch/helmfiles.yaml
  - ./helmfiles/kibana/helmfiles.yaml
