repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: prometheus
    namespace: efk
    chart: prometheus-community/prometheus
    values:
      - ./prometheus.yaml
