dashboards:
  enabled: false
  
fileConfigs:
  02_filters.conf: |-
    <label @KUBERNETES>
      <match kubernetes.var.log.containers.fluentd**>
        @type relabel
        @label @FLUENT_LOG
      </match>

      <match kubernetes.var.log.containers.**_kube-system_**>
        @type null
        @id  
      </match>

      <filter kubernetes.**>
        @type kubernetes_metadata
        @id filter_kube_metadata
        skip_labels false
        skip_container_metadata false
        skip_namespace_metadata true
        skip_master_url true
        suppress_type_name true
      </filter>

      <match **>
        @type relabel
        @label @DISPATCH
      </match>
    </label>

  04_outputs.conf: |-
    <label @OUTPUT>
      <match **>
        @type elasticsearch
        host "elasticsearch-master-hl"
        port 9200
        path ""
        user elastic
        password ""
        # Don't wait for elastic to start up.
        verify_es_version_at_startup false
      </match>
    </label>
