repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
releases:
  # need spec. colima start --cpu 8 --memory 16 --disk 200
  - name: elasticsearch
    namespace: efk
    chart: bitnami/elasticsearch
    version: 21.4.1
    values:
      - ./values.yaml
